name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_pgsql

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copy environment file
        run: cp .env.test .env

      # 🧪 Étape 1 : Lancer les tests unitaires
      - name: Run PHPUnit tests
        run: php vendor/bin/phpunit --coverage-text

      # 🧩 Étape 2 : Vérifier la qualité du code avec PHPStan
      - name: Run PHPStan
        run: php vendor/bin/phpstan analyse --no-progress

      # 🧹 Étape 3 : Vérifier le style du code avec PHP CS Fixer
      - name: Run PHP CS Fixer
        run: php vendor/bin/php-cs-fixer fix --dry-run --diff
